# Development Notebook

I use this notebook as a development tool.

# Preliminaries

In [1]:
%load_ext lab_black

## Imports

In [2]:
import numpy as np
import pandas as pd
import os

import sklearn
from sklearn.datasets import load_iris

In [3]:
from also_anomaly_detector import AlsoAnomalyDetector

# Data

In [4]:
iris = load_iris()

X = iris.get("data")
y = iris.get("target")

matrix = np.c_[X, y]

# Implementation

This is where functions and classes are implemented.

In [5]:
from sklearn.tree import DecisionTreeClassifier, DecisionTreeRegressor

# Sandbox

This is where functions and classes are tested.

In [6]:
clf = AlsoAnomalyDetector(max_depth=2, verbose=False)
clf.fit(
    X,
)

In [7]:
X.shape

(150, 4)

In [8]:
clf.residuals.shape

(150, 4)

In [9]:
clf.rrses

array([0.50904785, 0.73401218, 0.27454531, 0.29073937])

In [10]:
np.minimum([1, 1, 8], np.ones(3) * 3)

array([1., 1., 3.])

In [11]:
clf.scores.min(), clf.scores.mean(), clf.scores.max(),

(0.04213457370061215, 0.33174059795757, 0.9812469136088079)

In [16]:
clf.scores[clf.labels == 1]

array([0.60495527, 0.63661264, 0.62534942, 0.64214974, 0.66525965,
       0.76180275, 0.67113197, 0.64987086, 0.94315326, 0.668262  ,
       0.88395069, 0.71223524, 0.98124691, 0.69535764, 0.82635327])

In [13]:
clf.n_anomalies

15.0